/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-strophe.h
 #	source generated by 4D Plugin Wizard
 #	Project : strophe
 #	author : miyako
 #	2019/10/11
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_STROPHE_H
#define PLUGIN_STROPHE_H

#include "4DPluginAPI.h"
#include "strophe.h"

#include "json.h"

#include "4DPlugin-JSON.h"

#pragma mark -

void OnStartup();
void OnExit();

typedef enum {
 xmpp_stanza_type_message = 0,
 xmpp_stanza_type_connect = 1
}xmpp_stanza_type_t;

void xmpp_send(PA_PluginParameters params, xmpp_stanza_type_t type);

#endif /* PLUGIN_STROPHE_H */
